services:
  api:  
    build: 
      context: ./first
      dockerfile: Dockerfile
    image: node-api-img:1.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./first:/app
    environment:
      API_KEY: jhdsaoigfhaoihdjgoih